### ISSUE TITLE
Install_macOS process: Failed Error

### ISSUE THREAD

**Issue by memile123** [MLBZ521/upgrade_macOS#2]
This maybe my doing, but i am running into an issue when deploying through JAMF.  Some additional background:
-I created a policy that drops the mojave.app into the /Applications directory then i have the script to run after. I assumed parameter 4 was where we needed to define the OS version? could that be where this issue is? I'd also like to use the customer trigger but i am not too sure which parameter to set the that in, any insight would be helpful.

**Comment by MLBZ521** [comment]
@memile123 Sorry for the delay, I didn't get a notification for this error for some reason.

Correct, in Parameter 4, you should set the OS Version
 * i.e.  `Mojave` or `10.14`

For the Custom Trigger, you'd have to define that _inside_ the script.  There's a section at the top of the script to define variables:
 * `# Define Environmental Variables`

What error is being returned when the scripts run?  That'll give me a little info to go on as well.

**Comment by memile123** [comment]
![img_0369](https://user-images.githubusercontent.com/40469308/47577759-b2141000-d915-11e8-90d1-95df5a2dfe82.jpg)

@MLBZ521 Thanks for the response. I was able to get the script to load but its stuck at the attached screen. I've tried testing it with both an admin and standard user account. The Installer is in its right directory.

**Comment by MLBZ521** [comment]
@memile123 Sorry for the delay.  I had a busy weekend (my son's birthday).

So, the script properly downloads the Install.app (or it's already "staged") and then does nothing?

I'm assuming the script does "complete" and so, doesn't report back to Jamf.

Have you tried running the script locally on a machine (not from Jamf)?  Additionally, you can change the value on [L246](https://github.com/MLBZ521/install_macOS/blob/560e1bbbd9b4270baa9c1606b962c665f1bf6b3f/install_macOS.sh#L246) from `fs` to `hud`
- `windowType="fs"`
- `windowType="hud"`

So that it's not Full Screen and you can monitor the output from Terminal.

Knowing where it's stopping will help determine what's going on.

**Comment by memile123** [comment]
@MLBZ521 Hope you had fun! Thanks for replying back. It runs along with the script. After it drops in the directory, then the script runs. I have not ran it locally. I will do that in the tomorrow and send you an update along with what jamf/machine is showing.

**Comment by MLBZ521** [comment]
Sounds good.  I'll watch for a reply.

**Comment by MLBZ521** [comment]
@memile123 Just wanted to follow up and see if you were able to get this script to work for you?
